events {}

http {
  server {
    listen 80;

    # serve your index.html

    # proxy metabase
    location /metabase/ {
      proxy_pass http://metabase:3000/;

      # 🔑 REQUIRED for sub_filter to work
      proxy_set_header Accept-Encoding "";

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;

      sub_filter_once off;
      sub_filter_types text/html;

      proxy_hide_header Content-Security-Policy-Report-Only;


      # 🔥 REMOVE HEADER + FOOTER
      sub_filter '</head>' '
  <script>
  console.log("test")
  </script>
      </head>';
    }
  }
}
