#!/usr/bin/env python3
"""Generate UAT checklist CSV for the Webdesa admin dashboard."""

import csv
import sys

rows = [
    # ID, Module, Feature, Test Scenario, Pre-conditions, Steps, Expected Result, Priority, Type, Status
    # ===== 1. AUTHENTICATION =====
    ("AUTH-001", "Authentication", "Login", "Login with valid admin credentials",
     "User exists with admin role",
     "1. Navigate to /login. 2. Enter valid email and password (min 8 chars). 3. Click Login.",
     "User is redirected to /. Header shows avatar and name. access_token + refresh_token stored in localStorage.",
     "High", "Functional", ""),
    ("AUTH-002", "Authentication", "Login", "Login with invalid credentials",
     "—",
     "1. Navigate to /login. 2. Enter wrong email or password. 3. Click Login.",
     "Error message shown: 'Email atau kata sandi salah'. No redirect.",
     "High", "Functional", ""),
    ("AUTH-003", "Authentication", "Login", "Login with empty fields",
     "—",
     "1. Navigate to /login. 2. Leave email or password empty. 3. Click Login.",
     "Field-level validation: 'Bidang ini wajib diisi' for each empty field.",
     "Medium", "Validation", ""),
    ("AUTH-004", "Authentication", "Login", "Login with invalid email format",
     "—",
     "1. Enter 'not-an-email'. 2. Click Login.",
     "Field error: 'Email tidak valid'.",
     "Low", "Validation", ""),
    ("AUTH-005", "Authentication", "Login", "Login with password shorter than 8 chars",
     "—",
     "1. Enter valid email + 7-char password. 2. Click Login.",
     "Field error on password (min 8 chars).",
     "Low", "Validation", ""),
    ("AUTH-006", "Authentication", "Login", "Rate-limit (429) handling on login",
     "—",
     "1. Submit wrong credentials 6+ times in a row.",
     "After threshold: friendly rate-limit message 'Terlalu banyak percobaan. Silakan coba lagi nanti.'",
     "Medium", "Error Handling", ""),
    ("AUTH-007", "Authentication", "Login", "Authenticated user cannot revisit /login",
     "User already logged in",
     "1. While logged in, navigate to /login.",
     "Redirected to /.",
     "Low", "Routing", ""),
    ("AUTH-008", "Authentication", "Logout", "Logout clears session and routes to login",
     "User is logged in",
     "1. Click avatar dropdown in header. 2. Click Logout.",
     "Tokens cleared from localStorage and Pinia. Redirected to /login.",
     "High", "Functional", ""),
    ("AUTH-009", "Authentication", "Forgot Password", "Submit email for reset",
     "—",
     "1. Navigate to /forgot-password. 2. Enter valid email. 3. Submit.",
     "Confirmation screen shown ('Jika email terdaftar...').",
     "High", "Functional", ""),
    ("AUTH-010", "Authentication", "Forgot Password", "Rate-limit (429) on password reset",
     "—",
     "1. Submit password reset for the same email >5 times in an hour.",
     "Error message 'Terlalu banyak percobaan. Silakan coba lagi nanti.'",
     "Medium", "Error Handling", ""),
    ("AUTH-011", "Authentication", "Forgot Password", "Empty email rejected",
     "—",
     "1. Navigate to /forgot-password. 2. Submit empty form.",
     "Field error 'Email wajib diisi.'",
     "Low", "Validation", ""),
    ("AUTH-012", "Authentication", "Reset Password", "Reset password with valid token",
     "Valid ?token= in URL",
     "1. Open reset link from email. 2. Token validated on mount. 3. Enter new password (≥8) + confirm. 4. Submit.",
     "Password updated. Redirect to /login. Can log in with new password.",
     "High", "Functional", ""),
    ("AUTH-013", "Authentication", "Reset Password", "Reset password with invalid token",
     "Invalid or expired ?token=",
     "1. Open reset link with bogus token.",
     "Form blocked or shown as invalid.",
     "High", "Functional", ""),
    ("AUTH-014", "Authentication", "Reset Password", "Password mismatch rejected",
     "—",
     "1. Enter password and different confirmation. 2. Submit.",
     "Error message about mismatch.",
     "Medium", "Validation", ""),
    ("AUTH-015", "Authentication", "Session", "Token refresh on 401",
     "Access token expired but refresh token valid",
     "1. Wait until access token expires. 2. Trigger any API call.",
     "Single refresh call to /auth/refresh; original request retried; UI continues normally.",
     "High", "Integration", ""),
    ("AUTH-016", "Authentication", "Session", "Refresh failure routes to login",
     "Refresh token also invalid",
     "1. Manually expire refresh_token in localStorage. 2. Trigger API call.",
     "Tokens cleared. Redirected to /login.",
     "High", "Integration", ""),

    # ===== 2. DASHBOARD =====
    ("DASH-001", "Dashboard", "Stats", "All 4 stat cards display totals",
     "Logged in as admin with seeded data",
     "1. Navigate to /.",
     "Cards show: Users, Berita, UMKM, Fasilitas with non-zero counts from pagination.total.",
     "High", "Functional", ""),
    ("DASH-002", "Dashboard", "Stats", "Empty state when no data exists",
     "All resources empty",
     "1. Navigate to / with empty backend.",
     "Cards show 0.",
     "Medium", "Functional", ""),
    ("DASH-003", "Dashboard", "Loading", "Spinner shown while fetching",
     "—",
     "1. Navigate to / with throttled network.",
     "LoadingSpinner visible during fetch.",
     "Low", "UI", ""),

    # ===== 3. USER MANAGEMENT =====
    ("USER-001", "Users", "List", "List displays users with avatar, name, email, roles",
     "Admin user with seeded users",
     "1. Navigate to /users.",
     "Table populated. Roles shown as badges.",
     "High", "Functional", ""),
    ("USER-002", "Users", "Search", "Search filters by name/email",
     "—",
     "1. Type in search box. Wait 300ms.",
     "Table reloads with filtered results.",
     "High", "Functional", ""),
    ("USER-003", "Users", "Pagination", "Paginate through users",
     ">10 users exist",
     "1. Click page 2.",
     "Table shows next 10 users.",
     "Medium", "Functional", ""),
    ("USER-004", "Users", "Create", "Create user with valid data",
     "—",
     "1. Click 'Tambah User'. 2. Fill email, name, password (≥8), avatar (optional), roles. 3. Submit.",
     "User created. Redirect to /users. New user appears in list.",
     "High", "Functional", ""),
    ("USER-005", "Users", "Create", "Create with duplicate email",
     "—",
     "1. Try to create user with existing email.",
     "Server error displayed via notification toast.",
     "Medium", "Validation", ""),
    ("USER-006", "Users", "Create", "Required fields enforced",
     "—",
     "1. Submit form with missing email or name or short password.",
     "Field-level errors block submit.",
     "High", "Validation", ""),
    ("USER-007", "Users", "Edit", "Edit user details and roles",
     "Existing user",
     "1. Click Edit on a row. 2. Change name and roles. 3. Submit.",
     "User updated. Roles synced via POST/DELETE per role diff.",
     "High", "Functional", ""),
    ("USER-008", "Users", "Delete", "Delete user via confirm dialog",
     "—",
     "1. Click Delete on a row. 2. Confirm.",
     "User deleted. Row removed from list.",
     "High", "Functional", ""),
    ("USER-009", "Users", "Delete", "Self-row delete hidden",
     "Logged in as admin",
     "1. Find own row in /users.",
     "No Delete button on own row.",
     "Medium", "Security", ""),
    ("USER-010", "Users", "Password Reset", "Admin resets another user's password",
     "—",
     "1. Edit user. 2. In password section, enter new_password (no old_password required). 3. Submit.",
     "Password updated.",
     "High", "Functional", ""),
    ("USER-011", "Users", "RBAC", "Non-admin cannot access /users",
     "User without admin role",
     "1. Log in as operator. 2. Navigate to /users.",
     "Redirected to /.",
     "High", "Security", ""),
    ("USER-012", "Users", "Image", "Avatar upload + preview",
     "—",
     "1. Edit user. 2. Drop or pick a JPEG/PNG/WebP under 2MB.",
     "Preview shown. Submit uploads and image displays in list.",
     "Medium", "Functional", ""),
    ("USER-013", "Users", "Image", "Invalid image type rejected",
     "—",
     "1. Drop a .gif or .pdf.",
     "Error shown, no preview.",
     "Low", "Validation", ""),

    # ===== 4. MY PROFILE =====
    ("ME-001", "My Profile", "View", "Display own profile",
     "Logged in",
     "1. Navigate to /me.",
     "Avatar, name, email, roles shown.",
     "High", "Functional", ""),
    ("ME-002", "My Profile", "Edit", "Update name + avatar",
     "—",
     "1. Click Edit. 2. Change name/avatar. 3. Save.",
     "Profile updated. Header avatar refreshes.",
     "High", "Functional", ""),
    ("ME-003", "My Profile", "Password", "Change own password with old password",
     "—",
     "1. Click Change Password. 2. Enter old + new (≥8) + confirm. 3. Submit.",
     "Password changed. Modal closes.",
     "High", "Functional", ""),
    ("ME-004", "My Profile", "Password", "Mismatched confirmation rejected",
     "—",
     "1. New and confirm differ.",
     "Error shown.",
     "Medium", "Validation", ""),
    ("ME-005", "My Profile", "Password", "Short new password rejected",
     "—",
     "1. New password <8 chars.",
     "Error shown.",
     "Low", "Validation", ""),

    # ===== 5. ROLES & PERMISSIONS =====
    ("ROLE-001", "Roles", "List", "List shows roles with user counts",
     "—",
     "1. Navigate to /roles.",
     "Roles table with Name, User Count, Actions.",
     "High", "Functional", ""),
    ("ROLE-002", "Roles", "Create", "Create custom role",
     "—",
     "1. Open create modal. 2. Enter unique name. 3. Submit.",
     "Role appears in list.",
     "High", "Functional", ""),
    ("ROLE-003", "Roles", "Delete", "Delete custom role",
     "Custom role with no users",
     "1. Click delete on custom role.",
     "Role removed.",
     "High", "Functional", ""),
    ("ROLE-004", "Roles", "Delete", "Default roles (admin, operator) protected",
     "—",
     "1. Find admin/operator in list.",
     "No delete button.",
     "Medium", "Security", ""),
    ("ROLE-005", "Roles", "Permissions", "Edit permission matrix",
     "—",
     "1. Click manage permissions on a role. 2. Toggle checkboxes. 3. Save.",
     "Permissions synced: diff-and-send POST (add) + DELETE (remove).",
     "High", "Functional", ""),
    ("ROLE-006", "Roles", "Permissions", "No-op save when nothing changed",
     "—",
     "1. Open permissions modal and close without changes.",
     "No network call.",
     "Low", "Functional", ""),
    ("ROLE-007", "Roles", "i18n", "All labels translated when language=en",
     "—",
     "1. Switch to English. 2. Open /roles.",
     "All column headers, modal labels, buttons in English.",
     "Low", "i18n", ""),

    # ===== 6. BANNER =====
    ("BAN-001", "Banners", "List", "List shows all banners with thumbnails",
     "—",
     "1. Navigate to /banners.",
     "Thumbnails + judul + caption + status badge.",
     "High", "Functional", ""),
    ("BAN-002", "Banners", "Filter", "Filter by status",
     "—",
     "1. Select 'Aktif' or 'Nonaktif' from dropdown.",
     "List filtered.",
     "High", "Functional", ""),
    ("BAN-003", "Banners", "Create", "Create banner with image",
     "—",
     "1. Click Tambah Banner. 2. Fill title, caption, image (required), status. 3. Submit.",
     "Banner created.",
     "High", "Functional", ""),
    ("BAN-004", "Banners", "Create", "Missing required image rejected",
     "—",
     "1. Submit create form without image.",
     "Error or 400 from server.",
     "Medium", "Validation", ""),
    ("BAN-005", "Banners", "Edit", "Edit and replace image",
     "—",
     "1. Edit banner. 2. Replace image. 3. Submit.",
     "New image shown in list.",
     "High", "Functional", ""),
    ("BAN-006", "Banners", "Status", "Inline status toggle",
     "—",
     "1. Click status badge → choose toggle option.",
     "PATCH /banners/{id}/status called; badge updates.",
     "High", "Functional", ""),
    ("BAN-007", "Banners", "Delete", "Delete with confirm",
     "—",
     "1. Click delete on row. 2. Confirm.",
     "Banner removed.",
     "High", "Functional", ""),

    # ===== 7. NEWS / BERITA =====
    ("NEWS-001", "News", "List", "List with cover, title, category, date",
     "—",
     "1. Navigate to /berita.",
     "Table populated.",
     "High", "Functional", ""),
    ("NEWS-002", "News", "Filter", "Filter by search, category, date range",
     "—",
     "1. Type in search. 2. Pick category. 3. Pick date range.",
     "List reloads with combined filters.",
     "High", "Functional", ""),
    ("NEWS-003", "News", "Create", "Create with title + body + image",
     "—",
     "1. Click Tambah Berita. 2. Fill required fields. 3. Pick image. 4. Submit.",
     "Berita created.",
     "High", "Functional", ""),
    ("NEWS-004", "News", "Rich Text", "Body accepts formatted text",
     "—",
     "1. Use Quill toolbar (bold, italic, headers, lists, tables).",
     "Body saved with HTML formatting.",
     "High", "Functional", ""),
    ("NEWS-005", "News", "Rich Text", "Inline image upload via Quill",
     "—",
     "1. Click image button in Quill. 2. Pick an image.",
     "Image uploaded via /berita/upload-media; inserted at cursor.",
     "Medium", "Functional", ""),
    ("NEWS-006", "News", "Rich Text", "Inline video upload via Quill",
     "—",
     "1. Click video button in Quill. 2. Pick a video.",
     "Video uploaded and embedded.",
     "Medium", "Functional", ""),
    ("NEWS-007", "News", "Category", "Free-text category creates new on submit",
     "—",
     "1. Type a brand-new name in category input. 2. Submit form.",
     "Backend creates the category (returns UUID). Form submits with category=<UUID>.",
     "High", "Functional", ""),
    ("NEWS-008", "News", "Category", "Datalist autocomplete shows existing categories",
     "—",
     "1. Focus category input.",
     "Existing category names appear as suggestions.",
     "Medium", "UX", ""),
    ("NEWS-009", "News", "Category", "Open category manager modal",
     "—",
     "1. Click 'Kelola Kategori' button.",
     "Modal opens listing existing categories with their UUIDs.",
     "High", "Functional", ""),
    ("NEWS-010", "News", "Category", "Add category via modal",
     "—",
     "1. In modal, type name + click Tambah.",
     "New category appears in list with UUID assigned by backend.",
     "High", "Functional", ""),
    ("NEWS-011", "News", "Category", "Delete category via modal",
     "—",
     "1. Click delete on a category.",
     "DELETE /berita/categories/{id} called. Category removed.",
     "High", "Functional", ""),
    ("NEWS-012", "News", "Category", "Delete in-use category returns 409",
     "Category assigned to a berita",
     "1. Try to delete that category in modal.",
     "Error toast: 'Kategori masih digunakan dan tidak dapat dihapus'.",
     "Medium", "Error Handling", ""),
    ("NEWS-013", "News", "Category", "Click category in modal selects {id, name}",
     "—",
     "1. Click a category in modal.",
     "Modal closes. form.category = {id, name}. UUID shown below input.",
     "Medium", "UX", ""),
    ("NEWS-013a", "News", "Category", "Submit sends UUID, not name",
     "Existing category 'Pengumuman'",
     "1. Select 'Pengumuman' in modal. 2. Submit. 3. Inspect network.",
     "Request body contains `category=<UUID>` not `category=Pengumuman`.",
     "High", "Integration", ""),
    ("NEWS-013b", "News", "Category", "Edit mode pre-fills category UUID",
     "Existing berita with category",
     "1. Open edit page.",
     "form.category populated with {id, name} from response.category_id + response.category.name.",
     "High", "Functional", ""),
    ("NEWS-013c", "News", "Category", "Typing existing name resolves to its UUID",
     "—",
     "1. Type a name that matches an existing category. 2. Submit.",
     "Frontend resolves the UUID from suggestions; no new category is created.",
     "Medium", "Functional", ""),
    ("NEWS-014", "News", "Validation", "Empty title or body rejected",
     "—",
     "1. Submit without title or body.",
     "Field errors block submit.",
     "High", "Validation", ""),
    ("NEWS-015", "News", "Edit", "Edit preserves existing image when not replaced",
     "—",
     "1. Edit berita. 2. Don't replace image. 3. Submit.",
     "Image unchanged.",
     "Medium", "Functional", ""),
    ("NEWS-016", "News", "Delete", "Delete with confirm",
     "—",
     "1. Click delete on row. 2. Confirm.",
     "Berita removed.",
     "High", "Functional", ""),

    # ===== 8. UMKM =====
    ("UMKM-001", "UMKM", "List", "List with thumbnail, name, owner, category",
     "—",
     "1. Navigate to /umkm.",
     "Table populated.",
     "High", "Functional", ""),
    ("UMKM-002", "UMKM", "Search", "Search filters by name/owner",
     "—",
     "1. Type in search.",
     "List reloads after 300ms debounce.",
     "High", "Functional", ""),
    ("UMKM-003", "UMKM", "Create", "Create with multiple images",
     "—",
     "1. Tambah UMKM. 2. Fill name, owner, address, phone, email, website, category, description. 3. Pick multiple images. 4. Submit.",
     "UMKM created.",
     "High", "Functional", ""),
    ("UMKM-004", "UMKM", "Validation", "Required fields enforced",
     "—",
     "1. Submit without name/owner/address/phone.",
     "Field errors block submit.",
     "High", "Validation", ""),
    ("UMKM-005", "UMKM", "Validation", "Invalid phone format rejected",
     "—",
     "1. Enter 'abc' in phone.",
     "Error 'Format telepon tidak valid'.",
     "Medium", "Validation", ""),
    ("UMKM-006", "UMKM", "Edit", "Existing images re-fetched as blobs on update",
     "UMKM with images",
     "1. Edit UMKM. 2. Don't change images. 3. Submit.",
     "Images preserved (re-fetched and re-uploaded).",
     "High", "Functional", ""),
    ("UMKM-007", "UMKM", "Edit", "Add new image while preserving existing",
     "—",
     "1. Edit UMKM. 2. Add 1 new image. 3. Submit.",
     "Both old and new images present.",
     "High", "Functional", ""),
    ("UMKM-008", "UMKM", "Category", "Free-text creates + datalist + Kelola modal (UUID)",
     "—",
     "Repeat NEWS-007..013c for UMKM: submit sends category=<UUID>; edit pre-fills {id, name}; free text auto-creates.",
     "Same expected behaviors. UUIDs shown next to category names in modal.",
     "High", "Functional", ""),
    ("UMKM-009", "UMKM", "Delete", "Delete with confirm",
     "—",
     "1. Click delete. 2. Confirm.",
     "UMKM removed.",
     "High", "Functional", ""),

    # ===== 9. FASILITAS =====
    ("FAS-001", "Fasilitas", "List", "List displays facilities",
     "—",
     "1. Navigate to /fasilitas.",
     "Table populated.",
     "High", "Functional", ""),
    ("FAS-002", "Fasilitas", "Pagination", "Paginate through facilities",
     ">10 facilities",
     "1. Click next page.",
     "Next set shown.",
     "Medium", "Functional", ""),
    ("FAS-003", "Fasilitas", "Create", "Create with coordinates",
     "—",
     "1. Click Tambah. 2. Fill name, type, description, lat/lng, images. 3. Submit.",
     "Facility created.",
     "High", "Functional", ""),
    ("FAS-004", "Fasilitas", "Map", "Drag marker to update coords",
     "—",
     "1. Drag the marker on the inline map.",
     "Lat/Lng inputs update with marker position.",
     "High", "Functional", ""),
    ("FAS-005", "Fasilitas", "Map", "Click on map moves marker",
     "—",
     "1. Click anywhere on the map.",
     "Marker moves; lat/lng update.",
     "Medium", "Functional", ""),
    ("FAS-006", "Fasilitas", "Map", "Marker constrained to village polygon",
     "—",
     "1. Try to drag marker outside polygon.",
     "Marker snaps back to polygon centroid.",
     "Medium", "Functional", ""),
    ("FAS-007", "Fasilitas", "Map", "Fullscreen map modal",
     "—",
     "1. Click fullscreen icon. 2. Pick precise point. 3. Close.",
     "Coord inputs reflect chosen point.",
     "Medium", "UX", ""),
    ("FAS-008", "Fasilitas", "Map", "Minimap visible in corner",
     "—",
     "1. View the map.",
     "Minimap rendered in corner.",
     "Low", "UI", ""),
    ("FAS-009", "Fasilitas", "Validation", "Latitude out of range rejected",
     "—",
     "1. Enter latitude >90 or <-90.",
     "Error 'Latitude harus antara -90 dan 90'.",
     "High", "Validation", ""),
    ("FAS-010", "Fasilitas", "Validation", "Longitude out of range rejected",
     "—",
     "1. Enter longitude >180 or <-180.",
     "Error 'Longitude harus antara -180 dan 180'.",
     "High", "Validation", ""),
    ("FAS-011", "Fasilitas", "Images", "Add multiple new images",
     "—",
     "1. Pick multiple files.",
     "Thumbnails shown.",
     "Medium", "Functional", ""),
    ("FAS-012", "Fasilitas", "Images", "Remove existing image calls DELETE endpoint",
     "Facility with images in edit mode",
     "1. Click × on an existing image.",
     "DELETE /fasilitas/{id}/images/{idx} called. Image disappears.",
     "High", "Functional", ""),
    ("FAS-013", "Fasilitas", "Images", "Roll back on delete failure",
     "—",
     "1. Disconnect network. 2. Click × on existing image.",
     "Error toast. Image restored.",
     "Medium", "Error Handling", ""),
    ("FAS-014", "Fasilitas", "Delete", "Delete with confirm",
     "—",
     "1. Click delete. 2. Confirm.",
     "Facility removed.",
     "High", "Functional", ""),

    # ===== 10. PPID =====
    ("PPID-001", "PPID", "List", "List with thumbnail, title, category, date",
     "—",
     "1. Navigate to /ppid.",
     "Table populated.",
     "High", "Functional", ""),
    ("PPID-002", "PPID", "Filter", "Filter by category UUID",
     "—",
     "1. Pick a category from dropdown. 2. Inspect network.",
     "Request includes `?category=<UUID>`. List reloads filtered by that UUID.",
     "High", "Functional", ""),
    ("PPID-003", "PPID", "Search", "Search by title",
     "—",
     "1. Type in search.",
     "List reloads after 300ms.",
     "High", "Functional", ""),
    ("PPID-004", "PPID", "Create", "Upload document with required file",
     "—",
     "1. Tambah Dokumen. 2. Fill title, category, optional description/publication date. 3. Upload document (PDF/DOC/XLS). 4. Optional thumbnail. 5. Submit.",
     "Document created.",
     "High", "Functional", ""),
    ("PPID-005", "PPID", "Validation", "Missing document file on create rejected",
     "—",
     "1. Submit without document.",
     "Error 'Dokumen wajib diunggah'.",
     "High", "Validation", ""),
    ("PPID-006", "PPID", "Validation", "Invalid file type rejected",
     "—",
     "1. Upload a .jpg as document.",
     "Rejected by FileUpload validation.",
     "Medium", "Validation", ""),
    ("PPID-007", "PPID", "Edit", "Edit document metadata without re-uploading",
     "—",
     "1. Edit document. 2. Change title. 3. Don't replace file. 4. Submit.",
     "Document updated; original file preserved.",
     "Medium", "Functional", ""),
    ("PPID-008", "PPID", "Download", "Download document via blob",
     "—",
     "1. Click Download on a row.",
     "File downloads to user's machine.",
     "High", "Functional", ""),
    ("PPID-009", "PPID", "Download Path", "Download URL hits singular /ppid/document/{id}/download",
     "—",
     "1. Click Download. Inspect network tab.",
     "Request URL matches /ppid/document/{id}/download (singular).",
     "High", "Integration", ""),
    ("PPID-010", "PPID", "Delete", "Delete with confirm",
     "—",
     "1. Click delete. 2. Confirm.",
     "Document removed.",
     "High", "Functional", ""),
    ("PPID-011", "PPID", "Category", "Free-text + datalist + Kelola modal (UUID)",
     "—",
     "Repeat NEWS-007..013c for PPID: submit sends category=<UUID>; edit pre-fills {id, name}.",
     "Same expected behaviors.",
     "High", "Functional", ""),
    ("PPID-012", "PPID", "Requests List", "View all access requests",
     "—",
     "1. Navigate to /ppid-requests.",
     "Table with requester, email, doc, purpose, status.",
     "High", "Functional", ""),
    ("PPID-013", "PPID", "Requests", "Filter requests by status",
     "—",
     "1. Filter by pending/approved/revoked.",
     "List filtered; status badges colored.",
     "Medium", "Functional", ""),
    ("PPID-014", "PPID", "Requests", "Approve pending request",
     "Request with status=pending",
     "1. Click approve. 2. Confirm.",
     "Status changes to approved.",
     "High", "Functional", ""),
    ("PPID-015", "PPID", "Requests", "Revoke approved request",
     "Request with status=approved",
     "1. Click revoke. 2. Confirm.",
     "Status changes to revoked.",
     "High", "Functional", ""),

    # ===== 11. STRUKTUR =====
    ("STR-001", "Struktur", "List", "List with photo, name, position",
     "—",
     "1. Navigate to /struktur.",
     "Table populated.",
     "High", "Functional", ""),
    ("STR-002", "Struktur", "Search", "Search by name/position",
     "—",
     "1. Type in search.",
     "List filtered after 300ms.",
     "High", "Functional", ""),
    ("STR-003", "Struktur", "Create", "Create official with photo",
     "—",
     "1. Click Tambah. 2. Fill name, position, photo, optional contact. 3. Submit.",
     "Official added.",
     "High", "Functional", ""),
    ("STR-004", "Struktur", "Edit", "Edit via modal",
     "—",
     "1. Click Edit on row. 2. Update fields. 3. Submit.",
     "Official updated.",
     "High", "Functional", ""),
    ("STR-005", "Struktur", "Delete", "Delete with confirm",
     "—",
     "1. Click delete. 2. Confirm.",
     "Official removed.",
     "High", "Functional", ""),

    # ===== 12. VILLAGE PROFILE =====
    ("DESA-001", "Village Profile", "View", "Display village identity",
     "—",
     "1. Navigate to /profile.",
     "Name, address, phone, email, website, vision/mission shown.",
     "High", "Functional", ""),
    ("DESA-002", "Village Profile", "Edit", "Edit fields and save",
     "—",
     "1. Click Edit. 2. Update fields. 3. Save.",
     "Profile saved; view mode re-shown.",
     "High", "Functional", ""),
    ("DESA-003", "Village Profile", "Validation", "Name required",
     "—",
     "1. Clear name and save.",
     "Error 'Nama wajib diisi'.",
     "Medium", "Validation", ""),
    ("DESA-004", "Village Profile", "Validation", "Invalid email rejected",
     "—",
     "1. Enter invalid email.",
     "Error shown.",
     "Low", "Validation", ""),
    ("DESA-005", "Village Profile", "Validation", "Website must start with http(s)://",
     "—",
     "1. Enter 'example.com' without protocol.",
     "Error shown.",
     "Low", "Validation", ""),

    # ===== 13. PROFILE SECTIONS =====
    ("PSEC-001", "Profile Sections", "List", "List with section_name, endpoint, state",
     "—",
     "1. Navigate to /profile/sections.",
     "Table populated; endpoint shown as code badge.",
     "High", "Functional", ""),
    ("PSEC-002", "Profile Sections", "Filter", "Filter by section_name + state",
     "—",
     "1. Pick filters.",
     "List filtered.",
     "High", "Functional", ""),
    ("PSEC-003", "Profile Sections", "Create", "Create section with rich text",
     "—",
     "1. Tambah. 2. Pick section_name. 3. Write content in Quill. 4. Submit.",
     "Section created; endpoint auto-generated.",
     "High", "Functional", ""),
    ("PSEC-004", "Profile Sections", "Endpoint", "Endpoint is read-only",
     "—",
     "1. Open create or edit form.",
     "Endpoint shown as read-only badge.",
     "Medium", "UI", ""),
    ("PSEC-005", "Profile Sections", "Edit", "Edit content + state",
     "—",
     "1. Click Edit. 2. Update content. 3. Submit.",
     "Section updated.",
     "High", "Functional", ""),
    ("PSEC-006", "Profile Sections", "Delete", "Delete with confirm",
     "—",
     "1. Click delete. 2. Confirm.",
     "Section removed.",
     "High", "Functional", ""),

    # ===== 14. INFOGRAPHIC =====
    ("INFO-001", "Infographic", "List", "List with title, type, state",
     "—",
     "1. Navigate to /infographic.",
     "Table populated.",
     "High", "Functional", ""),
    ("INFO-002", "Infographic", "Filter", "Filter by component_type + state",
     "—",
     "1. Pick filters.",
     "List filtered.",
     "High", "Functional", ""),
    ("INFO-003", "Infographic", "Create", "Create with component_type + component_id",
     "—",
     "1. Tambah. 2. Title, pick type (dashboard/question), component_id, state. 3. Submit.",
     "Infographic created; preview updates live.",
     "High", "Functional", ""),
    ("INFO-004", "Infographic", "Preview", "Live preview updates on type/id change",
     "—",
     "1. Change component_type or component_id.",
     "Preview pane re-fetches token and re-renders.",
     "High", "Functional", ""),
    ("INFO-005", "Infographic", "Preview", "Metabase embed.js loaded once",
     "—",
     "1. Open form. 2. Inspect network.",
     "embed.js loaded once, not per component change.",
     "Medium", "UX", ""),
    ("INFO-006", "Infographic", "Modal Preview", "Preview from list via modal",
     "—",
     "1. Click Preview on a row.",
     "AppModal opens with metabase embed.",
     "High", "Functional", ""),
    ("INFO-007", "Infographic", "Edit", "Edit fields and update",
     "—",
     "1. Click Edit. 2. Change fields. 3. Submit.",
     "Infographic updated.",
     "High", "Functional", ""),
    ("INFO-008", "Infographic", "Delete", "Delete with confirm",
     "—",
     "1. Click delete. 2. Confirm.",
     "Infographic removed.",
     "High", "Functional", ""),

    # ===== 15. UI / CROSS-CUTTING =====
    ("UI-001", "UI", "Theme", "Toggle dark mode",
     "—",
     "1. Click theme toggle in header.",
     "<html> gets 'dark' class. All colors invert. Preference persisted in localStorage.",
     "High", "UI", ""),
    ("UI-002", "UI", "Theme", "Theme persists across reload",
     "—",
     "1. Toggle dark mode. 2. Reload page.",
     "Dark mode preserved (no flash).",
     "High", "UI", ""),
    ("UI-003", "UI", "Locale", "Switch language to English",
     "—",
     "1. Click language switcher → English.",
     "RoleListView labels translate. localStorage updated.",
     "Medium", "i18n", ""),
    ("UI-004", "UI", "Locale", "Switch back to Indonesian",
     "—",
     "1. Switch language → Indonesia.",
     "RoleListView labels in Indonesian.",
     "Medium", "i18n", ""),
    ("UI-005", "UI", "Sidebar", "Sidebar collapses to icon-only on desktop",
     "Wide viewport",
     "1. Click collapse toggle.",
     "Sidebar shows icons only. State persisted.",
     "Medium", "UI", ""),
    ("UI-006", "UI", "Sidebar", "Mobile sidebar hides by default",
     "Narrow viewport (<768px)",
     "1. Resize browser. 2. Reload.",
     "Sidebar hidden. Hamburger button visible.",
     "Medium", "UI", ""),
    ("UI-007", "UI", "Mobile", "Sidebar opens on hamburger click",
     "—",
     "1. Click hamburger.",
     "Sidebar slides in. Backdrop shown.",
     "Medium", "UI", ""),
    ("UI-008", "UI", "Breadcrumbs", "Breadcrumbs reflect route hierarchy",
     "—",
     "1. Navigate to /users/123/edit.",
     "Crumbs show: Dashboard / Users / Edit User.",
     "Medium", "UI", ""),
    ("UI-009", "UI", "Breadcrumb", "Breadcrumb for Profil Desa submenu",
     "—",
     "1. Navigate to /profile/sections.",
     "Crumbs include Profil Desa section.",
     "Low", "UI", ""),
    ("UI-010", "UI", "Toast", "Success toast auto-dismisses after ~3s",
     "—",
     "1. Trigger any success (e.g. save).",
     "Toast appears top-right then fades.",
     "Low", "UI", ""),
    ("UI-011", "UI", "Toast", "Error toast is sticky until manually closed",
     "—",
     "1. Trigger an error.",
     "Toast stays until user clicks ×.",
     "Low", "UI", ""),
    ("UI-012", "UI", "Confirm Dialog", "Confirm dialog resolves Promise<boolean>",
     "—",
     "1. Click delete on any row. 2. Cancel.",
     "No deletion happens. Dialog closes.",
     "Medium", "Functional", ""),
    ("UI-013", "UI", "Confirm Dialog", "Confirm dialog destructive action proceeds",
     "—",
     "1. Click delete. 2. Confirm.",
     "Resource deleted.",
     "Medium", "Functional", ""),
    ("UI-014", "UI", "Modal", "Esc closes modal",
     "—",
     "1. Open any modal. 2. Press Esc.",
     "Modal closes.",
     "Low", "UI", ""),
    ("UI-015", "UI", "Modal", "Backdrop click closes modal",
     "—",
     "1. Click outside the modal card.",
     "Modal closes.",
     "Low", "UI", ""),
    ("UI-016", "UI", "Form", "Required fields show error state",
     "—",
     "1. Submit any form with empty required fields.",
     "Each empty required field shows red border + error text.",
     "Medium", "UI", ""),
    ("UI-017", "UI", "Layout", "Header avatar shows user name",
     "Logged in",
     "1. View any page.",
     "Avatar/name shown in header.",
     "Medium", "UI", ""),
    ("UI-018", "UI", "Layout", "404 for unknown routes",
     "—",
     "1. Navigate to /random-path.",
     "NotFoundView shown.",
     "Low", "Routing", ""),
    ("UI-019", "UI", "Responsive", "All forms usable on mobile width",
     "Narrow viewport",
     "1. Open forms at 375px width.",
     "Inputs stack vertically; no horizontal scroll.",
     "Medium", "UI", ""),

    # ===== 16. SECURITY / RBAC =====
    ("SEC-001", "Security", "RBAC", "Operator cannot reach admin-only routes",
     "User without admin role",
     "1. Log in as operator. 2. Try to navigate to /users.",
     "Redirected to /. Sidebar hides User Management.",
     "High", "Security", ""),
    ("SEC-002", "Security", "RBAC", "Operator cannot access users via direct API",
     "—",
     "1. As operator, capture token. 2. curl GET /users with token.",
     "403 Forbidden.",
     "High", "Security", ""),
    ("SEC-003", "Security", "Auth", "Protected route without token redirects",
     "Logged out",
     "1. Clear localStorage. 2. Navigate to /users.",
     "Redirected to /login.",
     "High", "Security", ""),
    ("SEC-004", "Security", "Auth", "Token in localStorage (not httpOnly cookie)",
     "—",
     "1. Login. 2. Inspect localStorage.",
     "Tokens visible (documented limitation).",
     "Low", "Security", ""),
    ("SEC-005", "Security", "Auth", "Expired token triggers refresh once",
     "—",
     "1. Wait for access token to expire. 2. Make API call.",
     "Single refresh; original request retried; UI proceeds.",
     "High", "Integration", ""),
    ("SEC-006", "Security", "Auth", "No XSS via category name",
     "—",
     "1. Create category with name '<script>alert(1)</script>'. 2. View list.",
     "No script execution; name displayed as plain text.",
     "Medium", "Security", ""),
    ("SEC-007", "Security", "Files", "Reject oversized file uploads",
     "—",
     "1. Try to upload a 100MB file.",
     "Rejected with size error.",
     "Medium", "Security", ""),
    ("SEC-008", "Security", "Files", "Reject unsupported file types",
     "—",
     "1. Try to upload .exe as document.",
     "Rejected by type validation.",
     "Medium", "Security", ""),

    # ===== 17. INTEGRATION / SMOKE =====
    ("SMOKE-001", "Smoke", "Login flow", "End-to-end login → dashboard → logout",
     "—",
     "1. Open /login. 2. Submit valid creds. 3. Land on /. 4. Logout. 5. Land on /login.",
     "All transitions clean, no console errors.",
     "High", "Smoke", ""),
    ("SMOKE-002", "Smoke", "Create + edit + delete each resource", "Full CRUD pass across all resources",
     "Admin role, seeded backend",
     "1. For each resource (banner, berita, umkm, fasilitas, ppid, struktur, profile-section, infographic, user, role): create → edit → delete.",
     "All operations succeed; data persists across reload.",
     "High", "Smoke", ""),
    ("SMOKE-003", "Smoke", "Page reload preserves state", "Refresh keeps the user on the same page",
     "Logged in",
     "1. Navigate to /users. 2. Press F5.",
     "Still on /users; data reloaded.",
     "High", "Smoke", ""),
    ("SMOKE-004", "Smoke", "Multi-tab session", "Cross-tab data freshness",
     "Logged in",
     "1. Open /users in two tabs. 2. Edit a user in tab A.",
     "Tab B reflects change after refresh (no stale-data trap).",
     "Medium", "Smoke", ""),
    ("SMOKE-005", "Smoke", "Long session stability", "Session survives extended idle",
     "—",
     "1. Leave admin open for >1 hour. 2. Continue working.",
     "Refresh on 401 happens transparently.",
     "Medium", "Smoke", ""),
]

# Write CSV
output_path = "qa/UAT_CHECKLIST.csv"
with open(output_path, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_ALL)
    w.writerow(["ID", "Module", "Feature", "Test Scenario", "Pre-conditions", "Steps", "Expected Result", "Priority", "Type", "Status"])
    w.writerows(rows)

# Summary by module
from collections import Counter
modules = Counter(r[1] for r in rows)
priorities = Counter(r[7] for r in rows)
types = Counter(r[8] for r in rows)

print(f"Wrote {len(rows)} test cases to {output_path}")
print()
print("By module:")
for m, n in sorted(modules.items()):
    print(f"  {m:30s} {n}")
print()
print("By priority:")
for p, n in sorted(priorities.items()):
    print(f"  {p:10s} {n}")
print()
print("By type:")
for t, n in sorted(types.items()):
    print(f"  {t:15s} {n}")