linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - nilerr
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  govet:
    enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
    - path: integration/
      linters:
        - errcheck

run:
  timeout: 5m
  tests: true
